{{- if .Values.platform.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-conexs.name" . }}-client-svc
spec:
  ports:
  - name: http
    port: {{ .Values.global.client.port }}
    protocol: TCP
    targetPort: 8081
  selector:
    app: {{ include "web-conexs.name" . }}-client
  type: {{ .Values.client.service.type }}
{{- end }}
