{{- if .Values.platform.enabled}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pv-claim
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.data.storage }}
{{- end }}
