# Default values for xas-standards-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  #must match custom-init-scripts-volume in postgres section
  db_init_name: dbtables-configmap
  client:
    port: 8081
  api:
    port: 8080

platform:
  enabled: true

api:
  service:
    type: ClusterIP
    targetPort: 5000
  deployment:
    replicas: 1
    image:
      repository: ghcr.io/diamondlightsource/web-conexs-app-web-conexs-api
    resources:
      limits:
        cpu: "1"
        memory: 500M
  authz:
    type: ""
    url : ""
    base: ""
    attrKey: ""
    attrValue: ""
    opaurl: ""

client:
  service:
    type: ClusterIP
  deployment:
    replicas: 1
    image:
      repository: ghcr.io/diamondlightsource/web-conexs-app-web-conexs-client
    resources:
      limits:
        cpu: "1"
        memory: 500M

submitter:
  enabled: true
  deployment:
    image:
      repository: ghcr.io/diamondlightsource/web-conexs-app-web-conexs-api
    resources:
      limits:
        cpu: "1"
        memory: 1000M
  singularity:
      directory: ""
      pseudopotentialDir: ""
      coreDir: ""
      orca: ""
      fdmnes: ""
      quantumEspresso: ""
  slurm:
      api: ""
      partition: ""
      user: ""
      timelimit: ""
      responseKey: ""
      tokenFile: ""
      memory: ""
      cpus: ""
  extraVolumes: []
  extraVolumeMounts: []

database:
  enabled: true
  username: webconexsadmin
  dbname: webconexsdb
  protocol: "postgresql+psycopg2"
  passwordSecretName: application-passwords
  passwordSecretKey: passwords
  host: ""

auth:
  userInfoEndpoint: ""
  idKey: ""

data:
  location: /conexs_data/
  mountPath: /conexs_data
  storage: 10Gi
  rootDir: ""
  clusterRootDir: ""
  storageDays: "60"
  cleanupSchedule: "0 3 * * *"
  # extraVolumes:
  #   - name: data-pv-volume
  #     persistentVolumeClaim:
  #       claimName: data-pv-claim
  # extraVolumeMounts:
  #   - mountPath: {{ .Values.data.mountPath}}
  #     name: data-pv-volume


security:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    supplementalGroups: []
  

postgres:
  useDeployment: false
  backup:
    ## Enable backups through pgdumpall
    enabled: false
  ## Database and user (user is optional, but recommended, as 'postgres' would be the only user otherwise)
  userDatabase:
    ## Optional existing secret with database name, user and password
    existingSecret: conexs-app-postgres-passwords
    name: 
      ## Name of the user database
      secretKey: POSTGRES_DB
    password:
      ## Password of the database user
      secretKey: USER_PASS
    user:
      ## Database user with full access rights
      secretKey: USER_NAME
    ## Set host to use a custom host, remove to use DB release name
    #host: foo.diamond.ac.uk
    port: 5432
  ## Database configuration
  settings:
    ## Optional existing secret for the Postgrest superuser
    existingSecret: postgres-passwords
    superuserPassword:
      secretKey: password
  extraScripts: dbtables-configmap
  # tls:
  #   enabled: false
  #   certificatesSecret: ""
  #   certFilename: tls.crt
  #   certKeyFilename: tls.key

# alpha
oauth2-proxy:
  extraVolumeMounts:
    - name: proxy-secret
      mountPath: "/etc/alpha"
      readOnly: true
  extraVolumes:
    - name: proxy-secret
      secret:
        secretName: oidc-secrets
        items:
          - key: client-secret
            path: client-secret
  config:
    configFile: |-
      email_domains = [ "*" ]
      skip_auth_routes = ["GET=^/$","GET=^/assets","GET=^/conexs.svg$"]
      api_routes = ["^/api"]
      skip_provider_button = true
      cookie_refresh="1m"
      cookie_expire="30m"
  ingress:
    enabled: true
    pathType: Prefix
    hostname: ""
    hosts: []
    path: /
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "10M"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
  alphaConfig:
    enabled: true
    configFile: |
      upstreamConfig:
        proxyRawPath: true
        upstreams:
          - id: api
            path: /api/
            uri: http://{{ include "web-conexs.name" . }}-api-svc:{{.Values.global.api.port}}
          - id: client
            path: /
            uri: http://{{ include "web-conexs.name" . }}-client-svc:{{.Values.global.client.port}}
    configData:
      providers: []
      injectRequestHeaders:
         - name: Authorization
           values:
             - claimSource:
                 claim: access_token
                 prefix: "Bearer "
      injectResponseHeaders:
         - name: Identity
           values:
             - claimSource:
                 claim: id_token
  redis:
    enabled: false
